### ISSUE TITLE
Add weekday (จันทร์, อังคาร, …) to date sections

### ISSUE THREAD

**Issue by dtinth** [clousehub/thaiclubhouse#1]
![image](https://user-images.githubusercontent.com/193136/108192334-b6980e80-7146-11eb-9486-db35b2e6b750.png)

Make it display the weekday

## Suggested implementation solution

https://github.com/clousehub/thaiclubhouse/blob/250a43c7fbce70a1c1733fe6bd2411ddd01801c6/gen.php#L75

Change to

```php
      <tr><th colspan=2><h2><?=formatDate($cdate)?></h2></th></tr>
```

Then create a function `formatDate` that takes a string `YYYY-MM-DD` and return a date with more info.

**Comment by vtno** [comment]
@dtinth Can we consider this close? 😁

**Comment by dtinth** [comment]
Yes let’s close this, thanks!
